# Generated by Django 4.2.5 on 2023-12-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_subscriber_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('author_id', models.IntegerField()),
            ],
        ),
    ]
